#!/bin/sh
set -e

# Настройка ZRAM (4 ГБ)
# Загружаем модуль (если не загружен)
modprobe zram num_devices=1

# Сбрасываем устройство (на случай перезапуска сервиса)
swapoff /dev/zram0 2>/dev/null || true
echo 1 > /sys/block/zram0/reset

# Устанавливаем алгоритм сжатия lz4 (быстрый и эффективный)
echo lz4 > /sys/block/zram0/comp_algorithm
# Устанавливаем размер 4GB
echo 4G > /sys/block/zram0/disksize
# Форматируем и включаем с высоким приоритетом (100)
mkswap /dev/zram0 >/dev/null
swapon /dev/zram0 -p 100

# Удержание сервиса
exec pause
